finished adapting newfeature to use custom .temp_keys values to customize new branches names locally

diff --git a/newfeature b/newfeature
--- a/newfeature
+++ b/newfeature
@@ -30,11 +30,11 @@ show_help() {
     echo -e "                                                                                      will create a description like this ${reset} "
     echo -e "                                                                                     ${reset} "
     echo -e "   make a .describe filename with -> {                      ${reset} "
-    echo -e "                                 Allow for some method to measure the number of cache hits/misses in api.fronter.com  [38;5;33m  ${CURRENTDATE}                    ${reset} "
-    echo -e "                                [32m ‡ https://jira.company_name.com/browse/FRO-2681 (B[m  user_name  opened  [32m  ${CURRENT_LONG_DATE}  ${reset} "
+    echo -e "                                 Allow for some method to measure the number of cache hits/misses in api.fronter.com  [38;5;33m  }                    ${reset} "
+    echo -e "                                [32m ‡ https://jira.company_name.com/browse/FRO-2681 (B[m  user_name  opened  [32m  ${CURRENTLONG_DATE}  ${reset} "
     echo -e "      makes this filename ->    ${blue30} ${JOURNAL_HOME}/journals/api-endpoint/FRO-2681_Allow_for_some_method_to_measure_the_number_of_cache_hits  ${reset} "
-    echo -e "                                [38;5;238m _misses_in_api.fronter.com/${CURRENTDATE}_FRO-2681_Allow_for_some_method_to_measure_the_number_of_cache_hits_mis ${reset} "
-    echo -e "                                 [38;5;238mses_in_api.fronter.com_start.m  ${reset} "
+    echo -e "                                [38;5;238m _misses_in_api.fronter.com/}_FRO-2681_Allow_for_some_method_to_measure_the_number_of_cache_hits_mis ${reset} "
+    echo -e "                                 [38;5;238mses_in_api.fronter.com_stat.m  ${reset} "
     echo -e "                                (B[m from master or develop or gh-pages _BASEBRANCH_${reset} "
     echo -e "                                      }        ${reset} "
     echo -e " "
@@ -48,16 +48,31 @@ show_help() {
     echo -e "${blue30}            ${THISSCRIPTNAME} MDM-35  \"Fix no index SEO\" from gh-pages   ${reset}"
     echo -e ""
     echo -e ""
+    echo -e "${blue30}            ${THISSCRIPTNAME}  --debug "
+    echo -e "              start debugging and git create, pull, push will not be executed"
+    echo -e ""
 } # end show_help
 
-
+function msg_bullet() {
+	echo -e "${blue23} • ${blue30} ${@} ${reset}"
+}
+function msg_error() {
+	echo -e "${red} ERROR ! ${@} ${reset}"
+}
+function msg_warning() {
+	echo -e "${yellow220} WARNING ! ${@} ${reset}"
+}
 if [[ -z "$1"  ]] ; then  # if argument was not passed
     show_help
     exit 0;
 fi
 
+DEBUG_PROCESS=0
+[[ "${@}" == *"--debug"* ]] && DEBUG_PROCESS=1
+(( $DEBUG_PROCESS )) &&
+(( $DEBUG_PROCESS )) && echo -e "\\033[38;5;DEBUG_PROCESS: ON \\033[38;5;32m : ${DEBUG_PROCESS} :"
 
-echo -e "${blue23} • ${blue30} Prepare new Journal Entry ${reset}"
+msg_bullet Prepare new Journal Entry
 TICKETID="$1"
 DESCRIPTION=""
 NEWBRANCH="feature/${TICKETID}"
@@ -67,23 +82,19 @@ if [[ ! -z "$2"  ]] ; then
 	DESCRIPTION="$2"
 fi
 
-
 . $FOUND_DIR_JOURNAL/journal_get_target_branch
-
 . $FOUND_DIR_JOURNAL/journal_get_sed_functions
+JOURNALDIR=$(echo "${TICKETID}_${DESCRIPTION}"  | convert_to_underdash )
 
+#
+# Overwrite NEWBRANCH and - or - JOURNALDIR if values provided in local file .temp_keys  - START
+#
 JOURNAL_PROJECT_WORKING_ON=${PWD}
 [[ -e "$JOURNAL_PROJECT_WORKING_ON/.temp_keys" ]] && . $JOURNAL_PROJECT_WORKING_ON/.temp_keys
-
-
-JOURNALDIR=$(echo "${TICKETID}_${DESCRIPTION}"  | convert_to_underdash )
 
 if [[ ! -z "${JOURNAL_NEWBRANCH_STYLE_4_FEATURE}"  ]] ; then
 	NEWBRANCH="feature/${JOURNAL_NEWBRANCH_STYLE_4_FEATURE}"
 fi
-
-echo "${NEWBRANCH}"
-exit 1
 
 if [[ ! -z "${JOURNAL_JOURNALDIR_STYLE_4_FEATURE}"  ]] ; then
 	if [[ "${JOURNAL_JOURNALDIR_STYLE_4_FEATURE}" != "empty"  ]] ; then
@@ -92,80 +103,77 @@ if [[ ! -z "${JOURNAL_JOURNALDIR_STYLE_4_FEATURE}"  ]] ; then
 		JOURNALDIR=""
 	fi
 fi
+#
+# Overwrite NEWBRANCH and - or - JOURNALDIR if values provided in local file .temp_keys  - END
+#
 
 . $FOUND_DIR_JOURNAL/journal_get_project_name
 
-echo -e "${blue23} • ${blue30} Go to ${TARGETBASEBRANCH}  ${reset}"
-git checkout """${TARGETBASEBRANCH}"""
+msg_bullet Change branch to ${TARGETBASEBRANCH}
+(( ! $DEBUG_PROCESS )) && git checkout """${TARGETBASEBRANCH}"""
 
 . $FOUND_DIR_JOURNAL/journal_get_current_branch
 
 if [[ "${CURBRANCH}" != "${TARGETBASEBRANCH}"  ]] ; then
-	echo -e "${red} ERROR ! We did not switch to branch '${TARGETBASEBRANCH}' ${reset}"
-	exit 1;
+  msg_error We did not switch to branch
+	(( ! $DEBUG_PROCESS )) && exit 1
 fi
 # if file exists, I assume this is a shallow copy
 # REF: http://stackoverflow.com/questions/6941889/is-it-safe-to-shallow-clone-with-depth-1-create-commits-and-pull-updates-aga
-# REF: https://github.com/git/git/commit/9cfde9ee8f6dc82365f1e977935960f34108076b documentation on Shallow I viewd on 2016 07 July 02
+# REF: https://github.com/git/git/commit/9cfde9ee8f6dc82365f1e977935960f34108076b documentation on Shallow I viewed on 2016 07 July 02
 if [[ -f ".git/shallow" ]] ;	then
-	echo -e "${blue23} • ${blue30} This is a shallow REPO ${TARGETBASEBRANCH}  ${reset}"
-	git fetch --depth 1
-	git pull  --depth 1 origin """${TARGETBASEBRANCH}"""
-	#git pull  --progress --depth 1 origin """${TARGETBASEBRANCH}"""
+	msg_bullet This is a shallow REPO ${TARGETBASEBRANCH}
+	(( ! $DEBUG_PROCESS )) && git fetch --depth 1
+	(( ! $DEBUG_PROCESS )) && git pull  --depth 1 origin """${TARGETBASEBRANCH}"""
+	#(( ! $DEBUG_PROCESS )) && git pull  --progress --depth 1 origin """${TARGETBASEBRANCH}"""
 else
-	echo -e "${blue23} • ${blue30} This is a Normal repo.. not shallow ${TARGETBASEBRANCH}  ${reset}"
-	git fetch
-	git pull  origin """${TARGETBASEBRANCH}"""
-
+	msg_bullet This is a Normal repo.. not shallow ${TARGETBASEBRANCH}
+	(( ! $DEBUG_PROCESS )) && git fetch
+	(( ! $DEBUG_PROCESS )) && git pull  origin """${TARGETBASEBRANCH}"""
 fi
 
-
-echo -e "${blue23} • ${blue30} Create from ${TARGETBASEBRANCH}"
-echo -e "${blue23} • ${blue30} Create new branch ${green} """"${NEWBRANCH}""""${reset} using git flow ${reset}"
+msg_bullet Create from ${TARGETBASEBRANCH}
 if [[ "develop" == "${TARGETBASEBRANCH}"  ]] ; then
-	git flow feature start """${TICKETID}""";
+  msg_bullet Create new branch ${green} """"${NEWBRANCH}""""${yellow220} using git flow
+	#DEBUG # git flow feature start """${TICKETID}""";
 		if [ $? != 0 ]; then
-			echo -e "${yellow220} WARNING !  '${NEWBRANCH}' could not be created!. ${reset}"
+			msg_warning "'${NEWBRANCH}' could not be created!."
 		fi
 else
-	git checkout -b """${NEWBRANCH}""";  # This is set to "feature/${TICKETID}" line 47-ish above
+	# git checkout -b """${NEWBRANCH}""";  # This is set to "feature/${TICKETID}" line 47-ish above
 		if [ $? != 0 ]; then
-			echo -e "${yellow220} WARNING !  '${NEWBRANCH}' could not be created!. ${reset}"
+			msg_warning "'${NEWBRANCH}' could not be created!."
 		fi
 fi
 
 wait
 
 
-	CURBRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')          # correct output feature/TO-229
-
 	# Stop here to now ruin branch .. if we are still in ${TARGETBASEBRANCH}
 	if [[ "${CURBRANCH}" == "${TARGETBASEBRANCH}"  ]] ; then
-		echo -e "${yellow220} WARNING ! we are still in '${TARGETBASEBRANCH}' ${reset}"
-		echo -e "${blue23} • ${blue30} Trying two Create new branch """"${NEWBRANCH}"""" using regular branch creation ${reset}"
-		git checkout -b """${NEWBRANCH}""";
+		msg_warning "we are still in '${TARGETBASEBRANCH}'"
+		msg_bullet Trying two Create new branch """"${NEWBRANCH}"""" using regular branch creation
+		(( ! $DEBUG_PROCESS )) && git checkout -b """${NEWBRANCH}"""
 		if [ $? != 0 ]; then
-			echo -e "${yellow220} WARNING !  '${NEWBRANCH}' could not be created!. ${reset}"
+			msg_warning '${NEWBRANCH}' could not be created!.
 		fi
 		wait
-		CURBRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')          # correct output feature/TO-229
-		echo -e "${blue23} • ${blue30} Checking for branch """"${NEWBRANCH}"""" again ${reset}"
+
+. $FOUND_DIR_JOURNAL/journal_get_current_branch #Required to get branch once more after creating it, should be the same sa NEWBRANCH
+
+		msg_bullet Checking for branch """"${NEWBRANCH}"""" again
 		if [[ "${CURBRANCH}" == "${TARGETBASEBRANCH}"  ]] ; then
 			if [[ "${SAMEBRANCH}" == "YES"  ]] ; then
-				echo -e "${blue23} • ${blue30} Commiting and Base are the same ${reset}"
+				msg_bullet Commiting and Base are the same ${reset}
 			else
 				# Base branch should have been 'develop' or different from the current branch
-				echo -e "${red} ERROR ! we are still in ${TARGETBASEBRANCH} ${reset}"
+			  msg_error we are still in ${TARGETBASEBRANCH}
 				exit 1;
 			fi
 		fi
 	fi
 
-	CURRENTDATE=`date +%Y%m%d`
-	echo -e "${blue23} • ${blue30} New Feature Created: """"${CURBRANCH}""""${reset}";
-
-
-. $FOUND_DIR_JOURNAL/journal_get_journalentry_template
-. $FOUND_DIR_JOURNAL/journal_get_description_one_liner_construct
+(( ! $DEBUG_PROCESS )) && . $FOUND_DIR_JOURNAL/journal_get_journalentry_template
+(( ! $DEBUG_PROCESS )) && . $FOUND_DIR_JOURNAL/journal_get_description_one_liner_construct
 
 # :)
